% PjMolniya02SensorData creates artificial sensor data from the data
% generated by PjMolniya01GenerateData.m 

%% Dependencies
% Based on Code01NumIntegTwoBodyFiltering.m

% Calls fnGlobePlot.m, fnSensorSignal.m

% Requires data 'ActualEphemeris.mat' which is produced by
% PjMolniya01GenerateData.m

% Saves data in 'SensorMeasurements.mat' for processing by the subsequent
% project files.

%% Author
% Ashiv Dhondea, RRSG, UCT.
% Date: 11 October 2015

%% References

% 1. Tracking Filter Engineering. Norman Morrison
% 2. Statistical Orbit Determination. Tapley, Schutz, Born.

%% Clear memory
clear
clc
% close all;

%% Declare constants
mu = 398600;     % Earth’s gravitational parameter [km^3/s^2]
R_earth = 6378;  % Earth radius [km]

%% Declare variables

% Load ephemeris generated by Code01NumIntegTwoBody.m
load('ActualEphemeris.mat')

%% Generate sensor output signal

StandardDeviationX = 40;
StandardDeviationY = 20;
StandardDeviationZ = 10;

 Y  = fnSensorSignal( X,StandardDeviationX,StandardDeviationY,StandardDeviationZ );
 
%% Plotting
fnGlobePlot( Y, R_earth, -30, 20,1.5 )

%% Store data
data = 'SensorMeasurements.mat';
save(data,'Y','StandardDeviationX','StandardDeviationY','StandardDeviationZ');
%% End
% The data generated in this file is analysed in the project
% Code01NumIntegTwoBodyGNF
